---
layout: cv
title: Luis Fernando Mendoza's Resume
---
# Luis Fernando Mendoza
Business Intelligence, Data Analyst

<div id="webaddress">
<a href="datascience@byui.edu">datascience@byui.edu</a>
| <a href="https://byuidatascience.github.io/development.html">Data Science Program</a>
| <a href="https://www.linkedin.com/groups/13537407/">LinkedIn</a>
| <a href="https://github.com/byuids-resumes">GitHub</a>
</div>


## Education

`Expected April 2025`
__Brigham Young University - Idaho__, Rexburg, ID

- Majoring in Business Analytics
- Mainoring in Data Science


## Service and Work History

`Jan 2024 - Present · 4 mos`
__Data Analyst Intern__, Salt Lake City, UT

• Conducted SQL queries in Databricks, resulting in comprehensive financial analysis across 500+ columns and 15 tables for church properties in the U.S. and Canada.
• Implemented an Excel form with xlookups and lists, streamlining the collection of security code information for church properties and enhancing data accuracy.
• Developed an online Microsoft Form to evaluate landscape quality for church properties nationwide, providing valuable insights for property management decisions.
• Optimized PowerBI Power Query efficiency through strategic merges, transposing, filtering, and Dataflow sourcing, leading to faster data processing and improved reporting capabilities.
• Enhanced code optimization in PowerQuery Advance Editor and experimented with compressing PowerBI Reports into .json files using Python, resulting in streamlined data management processes.
• Developed and deployed a custom Microsoft Power App that successfully automated eight critical processes, resulting in significant time and resource savings.
• Mastered the creation of advanced custom DAX columns in PowerBI reporting, enabling more accurate and insightful financial analysis.
• Developed PowerBI reports to effectively communicate high-level financial and work order information to stakeholders across the U.S. and Canada, facilitating data-driven decision-making.

`Apr 2023- Jan 2024`
__System & Data Analyst__, Rexburg, ID

• Experienced Data Analyst specializing in Power BI for dynamic dashboard creation. Proficient in DAX measures, bookmarks, drillthroughs, and other Power BI tools.
• Developed and maintained Power BI performance reporting systems, delivering crucial insights to over 1000 daily customers.
• Optimized 70% of all Power BI visuals for mobile view, ensuring seamless access to critical data on the go. Enhanced accessibility and usability of reports for stakeholders across different platforms.
• Cut web incidents through CRM TeamDynamix Software rate by 12%, using technical, analytical, and communication skills to accurately identify user needs and provide effective solutions.

`Oct 2018 - Oct 2019`
__Operations Coordinator & Business Consultant__, Bogota, COL

• Coordinated the opening of the company with the hub, the operational and legal system in 2 months.
• Collaborated with the manager to Interview more than 100 job applicants in two weeks and hired 30.
• Improved the financial system of more than 150 businesses in 6 months.
• Managed a team of 15 financial analysts, driving improvements in the financial systems of over 1000 small companies in six months

`Dec 2014 - Sep 2018`
__Founder & Business Owner__, Bogota, COL

• Managed the sales of more than 5,000 product units in 4 years, loyalty to more than 50 customers, and negotiated with big supermarkets.
• Built company legally in 2 months, designed 3 innovative products, and got from the INVIMA the Sanitary Registration for Food and Beverage in 1 year.
• Controlled business finances, made advertising, and supervised the factory´s staff for over 4 years.

`Oct 2011- Oct 2013`
__International Volunteer__, Puebla, MX

• Maintained 80+ hour work week for two years, teaching Christian principles to hundreds of families and individuals.
• Supervised, motivated, and trained 160 other missionaries in communication, conflict-resolution, and leadership skills


<!-- ### Footer

Last updated: April 2024 -->